ControleDeContatos/Controllers/AlterarSenhaController.cs
using ControleDeContatos.Helper;
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace ControleDeContatos.Controllers
{
    
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly ISessao _sessao;
        public AlterarSenhaController(IUsuarioRepositorio usuarioRepositorio, ISessao sessao)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _sessao = sessao;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Alterar(AlterarSenhaModel alterarSenhaModel)
        {
            try
            {
                UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
                alterarSenhaModel.Id = usuarioLogado.Id;

                if (ModelState.IsValid)
                {
                    _usuarioRepositorio.AtualizarSenha(alterarSenhaModel);
                    TempData["MensagemSucesso"] = "Senha alterada com sucesso!";
                    return View("Index", alterarSenhaModel);
                }
                
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possível alterar a senha, tente novamente. Detalhe do erro: {erro.Message}";
                return View("Index", alterarSenhaModel);
            }
            return View();
            
        }
    }
}

ControleDeContatos/Controllers/UsuarioController.cs
using ControleDeContatos.Filters;
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace ControleDeContatos.Controllers
{
    [PaginaRestrita]
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        public UsuarioController(IUsuarioRepositorio usuarioRepositorio)
        {
            _usuarioRepositorio = usuarioRepositorio;
        }
        public IActionResult Index()
        {
            List<UsuarioModel> usuarios = _usuarioRepositorio.BuscarTodos();
            return View(usuarios);
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {
            UsuarioModel usuario = _usuarioRepositorio.ListarPorId(id);
            return View(usuario);
        }
        public IActionResult Apagar(int id)
        {
            _usuarioRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Criar(UsuarioModel usuario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _usuarioRepositorio.Adicionar(usuario);
                    TempData["MensagemSucesso"] = "Contato cadastrado com sucesso!";
                    return RedirectToAction("Index");

                }

                return View(usuario);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = "Ops, não conseguimos cadastrar o seu usuario, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Alterar(UsuarioSemSenhaModel usuarioSemSenhaModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuario = new UsuarioModel
                    {
                        Id = usuarioSemSenhaModel.Id,
                        Nome = usuarioSemSenhaModel.Nome,
                        Login = usuarioSemSenhaModel.Login,
                        Email = usuarioSemSenhaModel.Email,
                        Perfil = usuarioSemSenhaModel.Perfil
                    };

                    _usuarioRepositorio.Atualizar(usuario);
                    TempData["MensagemSucesso"] = "Usuário alterado com sucesso!";
                    return RedirectToAction("Index");
                }

                // Se o ModelState for inválido, volta para a view de edição
                return View("Editar", usuarioSemSenhaModel);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos alterar o seu usuário, tente novamente. Detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

    }
}

ControleDeContatos/Views/Index.cshtml
@using ControleDeContatos.Enums;
@model AlterarSenhaModel
@{
	ViewData["Title"] = "Alterar Senha do Usuário";
}

<div class="text-center">

	<h1 class="display-4 mt-4">Editar usuário:</h1>

</div>

<div>
	<form asp-controller="AlterarSenha" asp-action="Alterar" method="post">
		<input type="hidden" asp-for="Id" />

		<div class="mb-3">
			<label for="senha" class="form-label">Senha atual:</label>
			<input type="senhaAtual" asp-for="SenhaAtual" class="form-control" required placeholder="Digite a senha atual">
		</div>
		<div class="mb-3">
			<label for="senha" class="form-label">Nova senha:</label>
			<input type="senhaAtual" asp-for="NovaSenha" class="form-control" required placeholder="Digite a sua nova senha">
		</div>
		<div class="mb-3">
			<label for="senha" class="form-label">Confirmar a nova senha:</label>
			<input type="senhaAtual" asp-for="ConfirmarNovaSenha" class="form-control" required placeholder="Digite a confirmação da nova senha">
		</div>

		<button type="submit" class="btn btn-primary">Alterar</button>
		<a class="btn btn-secondary" asp-controller="Usuario" asp-action="Index" role="button">Voltar</a>
	</form>
</div>