ControleDeContatos/Controllers/ContatoController.cs
using ControleDeContatos.Filters;
using ControleDeContatos.Helper;
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace ControleDeContatos.Controllers
{
    [PaginaParaUsuarioLogado]

    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;
        private readonly ISessao _sessao;
        public ContatoController(IContatoRepositorio contatoRepositorio, ISessao sessao)
        {
            _contatoRepositorio = contatoRepositorio;
            _sessao = sessao;
        }
        public IActionResult Index()
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            List<ContatoModel> contatos = _contatoRepositorio.BuscarTodos(usuarioLogado.Id);
            return View(contatos);
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);
            return View(contato);
        }
        public IActionResult Apagar(int id)
        {
            _contatoRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Criar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
                    contato.UsuarioId = usuarioLogado.Id;
                    _contatoRepositorio.Adicionar(contato);
                    TempData["MensagemSucesso"] = "Contato cadastrado com sucesso!";
                    return RedirectToAction("Index");

                }

                return View(contato);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = "Ops, não conseguimos cadastrar o seu contato, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Alterar(ContatoModel contato)
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            contato.UsuarioId = usuarioLogado.Id;
            _contatoRepositorio.Atualizar(contato);
            return RedirectToAction("Index");
        }
    }
}

ControleDeContatos/Views/Contato/Criar.cshtml
@model ContatoModel;
@{
	ViewData["Title"] = "Criar Contato";
}

<div class="text-center">

	<h1 class="display-4 mt-4">Cadastrar Contato:</h1>

</div>

<div>
	<form asp-controller="Contato" asp-action="Criar" method="post">
		<div class="mb-3">
			<label for="nome" class="form-label">Nome</label>
			<input type="text" asp-for="Nome" class="form-control" required placeholder="Digite o nome do contato">
		</div>
		<div class="mb-3">
			<label for="email" class="form-label">E-Mail</label>
			<input type="email" asp-for="Email" class="form-control" required placeholder="Digite o e-mail do contato">
		</div>
		<div class="mb-3">
			<label for="celular" class="form-label">Celular</label>
			<input type="text" asp-for="Celular" class="form-control" required placeholder="Digite o celular do contato">
		</div>

		<button type="submit" class="btn btn-primary">Adicionar</button>
		<a class="btn btn-secondary" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
	</form>
</div>

ControleDeContatos/Views/Contato/Editar.cshtml
@model ContatoModel;
@{
	ViewData["Title"] = "Editar Contato";
}

<div class="text-center">

	<h1 class="display-4 mt-4">Editar Contato:</h1>

</div>

<div>
	<form asp-controller="Contato" asp-action="Alterar" method="post">

		<!-- Macete, é através do Id que se identifica o código entende a partir do que se deve alterar -->
		<input type="hidden" asp-for="Id"/>

		<div class="mb-3">
			<label for="nome" class="form-label">Nome</label>
			<input type="text" class="form-control" asp-for="Nome" required placeholder="Digite o nome do contato">
		</div>
		<div class="mb-3">
			<label for="email" class="form-label">E-Mail</label>
			<input type="email" class="form-control" asp-for="Email" required placeholder="Digite o e-mail do contato">
		</div>
		<div class="mb-3">
			<label for="celular" class="form-label">Celular</label>
			<input type="text" class="form-control" asp-for="Celular" required placeholder="Digite o celular do contato">
		</div>

		<button type="submit" class="btn btn-primary">Alterar</button>
		<a class="btn btn-secondary" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
	</form>
</div>

ControleDeContatos/Views/Contato/Index.cshtml
@model List<ContatoModel>
@{
    ViewData["Title"] = "Listagem de Contatos";
}
@{
	int contador = 1;
}

<div class="text-center" >

	<div class="d-grid gap-2 d-md-flex justify-content-md-start">
		<a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar" >Adicionar um novo contato</a>
	</div>

	<h1 class="display-4 mt-4">Listagem de Contatos:</h1>
	<table class="table" id="tableContatos">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Nome</th>
				<th scope="col">E-mail</th>
				<th scope="col">Celular</th>
				<th scope="col"></th>
			</tr>
		</thead>
		<tbody>
            @if (Model != null && Model.Any())
            {
                foreach (ContatoModel contato in Model)
                {
                    <tr>
						<th scope="row">@contador</th>
                        <td>@contato.Nome</td>
                        <td>@contato.Email</td>
                        <td>@contato.Celular</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="Editar">Editar</a>
								<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#apagarConfirmacao" data-contato-id="@contato.Id" data-contato-nome="@contato.Nome">
                                    Apagar
                                </button>
                            </div>
                        </td>
                    </tr>
					contador++;
                }
            }
		</tbody>
	</table>

	<!-- Modal apagarConfirmacao -->
	<div class="modal fade" id="apagarConfirmacao" tabindex="-1">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h1 class="modal-title fs-5" id="exampleModalLabel">Confirmação de apagar o contato</h1>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">

					<p>Realmente deseja apagar o contato <strong id="nomeContatoModal"></strong>?</p>

				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cancelar Exclusão</button>
					<a id="btnConfirmarDelete" class="btn btn-danger">Apagar Contato</a>
				</div>
			</div>
		</div>
	</div>

	@if (TempData["MensagemSucesso"] != null)
	{
		<!--Modal Sucesso-->
		<div class="modal" id="modalSucesso" tabindex="-1">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title">Modal title</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body alert alert-success" role="alert">
						@TempData["MensagemSucesso"]
					</div>
				</div>
			</div>
		</div>
	}

	@if(TempData["MensagemErro"]!= null)
	{
		<!-- Modal de erro -->
		<div class="modal fade" id="modalErro" tabindex="-1">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title text-danger">Erro</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
					</div>
					<div class="modal-body alert alert-danger" role="alert">
						@TempData["MensagemErro"]
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
					</div>
				</div>
			</div>
		</div>
	}



    @section Scripts {

        <script>

				 const modalApagar = document.getElementById('apagarConfirmacao');
			const btnConfirmarDelete = document.getElementById('btnConfirmarDelete');
			let contatoId = 0;

			// Quando o modal de confirmação for aberto, pega os dados do botão clicado
			if (modalApagar) {
				modalApagar.addEventListener('show.bs.modal', function (event) {
					const button = event.relatedTarget;
					contatoId = button.getAttribute('data-contato-id');
					const contatoNome = button.getAttribute('data-contato-nome');

					document.getElementById('nomeContatoModal').textContent = contatoNome;

					document.getElementById('btnConfirmarDelete').removeAttribute('href');
				});
			}

			// Ao clicar em "Apagar Contato"
			if (btnConfirmarDelete) {
				btnConfirmarDelete.addEventListener('click', function (e) {
					e.preventDefault(); // impede qualquer redirecionamento automático

					// Fecha o modal de confirmação
					const modal = bootstrap.Modal.getInstance(modalApagar);
					modal.hide();

					// Mostra o modal de sucesso
					const modalSucesso = new bootstrap.Modal(document.getElementById('modalSucesso'));
					modalSucesso.show();

					setTimeout(() => {
						window.location.href = `/Contato/Apagar/${contatoId}`;
					}, 2000);
				});
			}
        </script>
    }
</div>